### ISSUE TITLE
Build fails with JDK11

### ISSUE THREAD

**Issue by richardstartin** [RoaringBitmap/RoaringBitmap#277]
It seems that the java-allocation-instrumenter dependency fails on JDK11, by the looks of it because of a transitive dependency on an outdated version of ASM:

```
WARNING: Failed to instrument class.
java.lang.IllegalArgumentException
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.<init>(ClassReader.java:160)
	at com.google.monitoring.runtime.instrumentation.asm.ClassReader.<init>(ClassReader.java:143)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.instrument(AllocationInstrumenter.java:177)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.instrument(AllocationInstrumenter.java:210)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.transform(AllocationInstrumenter.java:157)
	at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:167)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.bootstrap(AllocationInstrumenter.java:141)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenter.premain(AllocationInstrumenter.java:117)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.monitoring.runtime.instrumentation.AllocationInstrumenterBootstrap.premain(AllocationInstrumenterBootstrap.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Oct 21, 2018 6:49:27 PM com.google.monitoring.runtime.instrumentation.AllocationInstrumenter instrument
```

See this [failed build](https://travis-ci.org/RoaringBitmap/RoaringBitmap/builds/444435015). This failed with OpenJDK and Oracle JDK alike.

**Comment by lemire** [comment]
I don't have OpenJDK 11 installed yet. 

Do you happen to have a fix proposal?

**Comment by richardstartin** [comment]
I don't know if the library in question is still maintained; the latest version is being used. Memory profiling can be done with JMH's GC profiler, which works with JDK11, so one solution would be to use JMH instead.

**Comment by lemire** [comment]
I have raised the issue upstream. Let us see if they respond.

Presumably, this failure is specific to one test which we can workaround on JDK11, right?

**Comment by lemire** [comment]
The library sure looks like it is maintained... there are commits this month... but they may be due for a new release.

**Comment by lemire** [comment]
We have updated the instrumenter library to its latest version.

**Comment by lemire** [comment]
If you want to discuss dropping support for JDK8, I am game, but I think we need some kind of justification considering that it effectively comes for free at this time.

**Comment by lemire** [comment]
Ok. Let us close this issue given that I effectively did as you recommended and dropped the memory subpackage.

**Comment by richardstartin** [comment]
What I mean is 6 builds at a time seem to get throttled. OpenJDK8 will be a going concern for a while so I would not suggest dropping it, but oraclejdk8 is nearly EOL. *jdk9 and *jdk10 are already obsolete, so I think you could get away with:
- openjdk8
- oraclejdk11
- openjdk11

**Comment by lemire** [comment]
Good.
