### ISSUE TITLE
NPE in ContainerAppender.appendToUnderlying()

### ISSUE THREAD

**Issue by jihoonson** [RoaringBitmap/RoaringBitmap#358]
Hi, I'm using Druid and recently saw the below error.

```
18:39:45.139 [task-runner-0-priority-0] ERROR org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner - Encountered exception while running task.
java.lang.RuntimeException: java.lang.NullPointerException
        at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:524) ~[druid-indexing-service-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:246) [druid-indexing-service-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.run(SeekableStreamIndexTask.java:167) [druid-indexing-service-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:419) [druid-indexing-service-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:391) [druid-indexing-service-0.15.1-incubating.jar:0.15.1-incubating]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
        at org.roaringbitmap.ContainerAppender.appendToUnderlying(ContainerAppender.java:126) ~[RoaringBitmap-0.8.0.jar:?]
        at org.roaringbitmap.ContainerAppender.flush(ContainerAppender.java:115) ~[RoaringBitmap-0.8.0.jar:?]
        at org.roaringbitmap.RoaringBitmapWriter.get(RoaringBitmapWriter.java:260) ~[RoaringBitmap-0.8.0.jar:?]
        at org.apache.druid.collections.bitmap.WrappedRoaringBitmap.iterator(WrappedRoaringBitmap.java:146) ~[druid-processing-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.incremental.IncrementalIndexAdapter$MutableBitmapValues.iterator(IncrementalIndexAdapter.java:210) ~[druid-processing-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.StringDimensionMergerV9$ConvertingBitmapValues.iterator(StringDimensionMergerV9.java:644) ~[druid-processing-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.StringDimensionMergerV9.mergeBitmaps(StringDimensionMergerV9.java:476) ~[druid-processing-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.StringDimensionMergerV9.writeIndexes(StringDimensionMergerV9.java:420) ~[druid-processing-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.IndexMergerV9.makeIndexFiles(IndexMergerV9.java:218) ~[druid-processing-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.IndexMergerV9.merge(IndexMergerV9.java:915) ~[druid-processing-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.IndexMergerV9.persist(IndexMergerV9.java:780) ~[druid-processing-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.IndexMergerV9.persist(IndexMergerV9.java:749) ~[druid-processing-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.persistHydrant(AppenderatorImpl.java:1264) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.access$100(AppenderatorImpl.java:109) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl$2.doCall(AppenderatorImpl.java:533) ~[druid-server-0.15.1-incubating.jar:0.15.1-incubating]
        at org.apache.druid.common.guava.ThreadRenamingCallable.call(ThreadRenamingCallable.java:44) ~[druid-core-0.15.1-incubating.jar:0.15.1-incubating]
        ... 4 more
```

It seems like `container` was null [here](https://github.com/RoaringBitmap/RoaringBitmap/blob/master/RoaringBitmap/src/main/java/org/roaringbitmap/ContainerAppender.java#L126), but not sure how it could be null.

Here is the code of `WrappedRoaringBitmap.iterator()` in Druid. [It just calls `RoaringBitmapWriter<MutableRoaringBitmap>.get().iterator()`](https://github.com/apache/incubator-druid/blob/master/processing/src/main/java/org/apache/druid/collections/bitmap/WrappedRoaringBitmap.java#L152).

```java
  public IntIterator iterator()
  {
    return writer.get().getIntIterator();
  }
```

`writer` is created as below:

```java
this.writer = RoaringBitmapWriter.bufferWriter().get();
```

and `BufferWizard` which is returned by `RoaringBitmapWriter.bufferWriter()` is:

```java
  class BufferWizard extends Wizard<MappeableContainer, MutableRoaringBitmap> {

    @Override
    protected Supplier<MappeableContainer> arraySupplier() {
      return () -> new MappeableArrayContainer(expectedContainerSize);
    }

    @Override
    protected Supplier<MappeableContainer> runSupplier() {
      return MappeableRunContainer::new;
    }

    @Override
    protected MutableRoaringBitmap createUnderlying(int initialCapacity) {
      return new MutableRoaringBitmap(new MutableRoaringArray(initialCapacity));
    }
  }
```

Since `arraySupplier` is used as `newContainer` in `ContainerAppender`, it looks like the returned value from `newContainer` can't be null. 

Am I missing something? Do you guys have any idea how it could be null?

**Comment by lemire** [comment]
Ping @richardstartin !

**Comment by richardstartin** [comment]
Is this related to unsynchronised multi threaded access?

**Comment by richardstartin** [comment]
@jihoonson does Druid iterate over bitmaps that are being built on a different thread to the one building the bitmap without synchronising reads and writes? This may have been benign before (the reads via the iterator would just have been racy) but since I added bitmap writers to Druid getting an iterator has the side effect of flushing any pending changes to the bitmap being built. I don’t think it’s possible for the container to be null without the initialisation of the variable having taken place on another thread without the modifications being “visible.”

@leventov do you have any ideas?

**Comment by jihoonson** [comment]
@richardstartin thanks for looking at this issue. I don't think reads and writes are happening without synchronization. The write thread is different from the read thread, but the read operation (persist operation in Druid) happens only when all write operations (indexing operation in Druid) are finished.

**Comment by richardstartin** [comment]
Ok, but as you point out yourself, null is never assigned to the container, so your stack trace shouldn’t be possible without some kind of JMM violation. 

I doubt it’s related but #359 stops the appended from capturing the container builder so it would save some memory if you pick up the release after it merges.

**Comment by leventov** [comment]
I believe this is a bug in Druid, I've created https://github.com/apache/incubator-druid/issues/8492 to track it.

**Comment by lemire** [comment]
@leventov I am going to close this issue here, re-open if we can be traced back to Roaring.
