### ISSUE TITLE
Roaring64Bitmap::and raises NPE

### ISSUE THREAD

**Issue by AChekroun** [RoaringBitmap/RoaringBitmap#436]
**Describe the bug**
Tested with v0.9.5 and v0.9.6
Roaring64Bitmap::and throws a NPE under specific conditions

```
 NullPointerException: Cannot read field "matchedContainerId" because "toolkit" is null
	at org.roaringbitmap.art.AbstractShuttle.remove(AbstractShuttle.java:100)
	at org.roaringbitmap.art.LeafNodeIterator.remove(LeafNodeIterator.java:65)
	at org.roaringbitmap.art.KeyIterator.remove(KeyIterator.java:34)
	at org.roaringbitmap.longlong.Roaring64Bitmap.and(Roaring64Bitmap.java:267)
```

**To Reproduce**

```
    @Test
    public void shouldNotThrowNPE(){
       
        var inputs = new long[]{5183829215128059904L};
        var crossers = new long[]{4413527634823086080L,4418031234450456576L,4421408934170984448L,4421690409147695104L,4421479302915162112L,4421426526357028864L,4421413332217495552L,4421416630752378880L,4421416905630285824L,4421417111788716032L,4421417128968585216L,4421417133263552512L,4421417134337294336L};

        var refRB = new Roaring64Bitmap();
        refRB.add(inputs);

        var crossRB = new Roaring64Bitmap();
        crossRB.add(crossers);

        // NPE
        crossRB.and(refRB);
    }
```

**Java version:**

OpenJdk 15.0.1.9 hotspot

Thanks for your time

**Comment by lemire** [comment]
@weijietong Can you have a look?

**Comment by blacelle** [comment]
FYI, I started having a look into https://github.com/blacelle/RoaringBitmap/tree/FixNPEIAE_436_437

**Comment by weijietong** [comment]
see PR: https://github.com/RoaringBitmap/RoaringBitmap/pull/440
