### ISSUE TITLE
Roaring64Bitmap::and throws an IllegalArgumentException 

### ISSUE THREAD

**Issue by AChekroun** [RoaringBitmap/RoaringBitmap#437]
**Describe the bug**
Tested with v0.9.5 and v0.9.6
Roaring64Bitmap::and throws an IllegalArgumentException under specific conditions

```
java.lang.IllegalArgumentException: fromIndex(2) > toIndex(1)
	at java.base/java.util.Arrays.rangeCheck(Arrays.java:718)
	at java.base/java.util.Arrays.mismatch(Arrays.java:7655)
	at org.roaringbitmap.ArraysShim.mismatch(ArraysShim.java:39)
	at org.roaringbitmap.art.Art.removeSpecifyKey(Art.java:130)
	at org.roaringbitmap.art.Art.removeSpecifyKey(Art.java:152)
	at org.roaringbitmap.art.AbstractShuttle.remove(AbstractShuttle.java:98)
	at org.roaringbitmap.art.LeafNodeIterator.remove(LeafNodeIterator.java:65)
	at org.roaringbitmap.art.KeyIterator.remove(KeyIterator.java:34)
	at org.roaringbitmap.longlong.Roaring64Bitmap.and(Roaring64Bitmap.java:267)
```

**To Reproduce**

```
       @Test
    public void shouldNotThrowIAE(){

        long[] inputs = new long[]{5183829215128059904L};
        long[] crossers = new long[]{4421416447812311717L, 4420658333523655893L, 4420658332008999025L};

        var referenceRB = new Roaring64Bitmap();
        referenceRB.add(inputs);

        var crossRB = new Roaring64Bitmap();
        crossRB.add(crossers);

        //IAE
        crossRB.and(referenceRB);
    }
```

**Java version:**

OpenJdk 15.0.1.9 hotspot

Thanks for your time

**Comment by lemire** [comment]
@weijietong Can you have a look?

**Comment by blacelle** [comment]
FYI, I started having a look into https://github.com/blacelle/RoaringBitmap/tree/FixNPEIAE_436_437

**Comment by weijietong** [comment]
see PR: https://github.com/RoaringBitmap/RoaringBitmap/pull/440
