### ISSUE TITLE
Roaring64Bitmap::and throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AChekroun** [RoaringBitmap/RoaringBitmap#438]
**Describe the bug**
Tested with v0.9.5 and v0.9.6
Roaring64Bitmap::and throws an ArrayIndexOutOfBoundsException under specific conditions

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 5 out of bounds for byte[4]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.roaringbitmap.longlong.IntegerUtil.shiftLeftFromSpecifiedPosition(IntegerUtil.java:53)
	at org.roaringbitmap.art.Node4.remove(Node4.java:110)
	at org.roaringbitmap.art.Art.removeSpecifyKey(Art.java:142)
	at org.roaringbitmap.art.Art.removeSpecifyKey(Art.java:152)
	at org.roaringbitmap.art.AbstractShuttle.remove(AbstractShuttle.java:98)
	at org.roaringbitmap.art.LeafNodeIterator.remove(LeafNodeIterator.java:65)
	at org.roaringbitmap.art.KeyIterator.remove(KeyIterator.java:34)
	at org.roaringbitmap.longlong.Roaring64Bitmap.and(Roaring64Bitmap.java:267)
```

**To Reproduce**

```
    @Test
    public void shouldNotThrowAIOOB(){
        long[] inputs = new long[]{5183829215128059904L};
        long[] crossers = new long[]{4413527634823086080L,4418031234450456576L,4421408934170984448L,4421127459194273792L,4420916352961740800L,4420863576403607552L,4420850382264074240L,4420847083729190912L,4420847358607097856L,4420847564765528064L,4420847616305135616L,4420847620600102912L,4420847623821328384L};
        var referenceRB = new Roaring64Bitmap();
        referenceRB.add(inputs);

        var crossRB = new Roaring64Bitmap();
        crossRB.add(crossers);

        //AIOOB
        crossRB.and(referenceRB);
    }
    }
```

**Java version:**

OpenJdk 15.0.1.9 hotspot

Thanks for your time

**Comment by lemire** [comment]
@weijietong Can you have a look?

**Comment by weijietong** [comment]
see PR: https://github.com/RoaringBitmap/RoaringBitmap/pull/440
