### ISSUE TITLE
Getting java.lang.ArrayIndexOutOfBoundsException: 255

### ISSUE THREAD

**Issue by nbatra** [RoaringBitmap/RoaringBitmap#511]
I am trying to read a Roaring64BitMap stored on HDFS and getting the following exception 

```
val hdfs = FileSystem.get(new Configuration())
val filePath = "/roaringBitMap/data/31455978"
val bitmap = new Roaring64Bitmap
val input = new DataInputStream(hdfs.open(new Path(filePath) ))
try{
      bitmap.deserialize(input)
    }catch{
      case e: Exception => e.printStackTrace()
    }finally {
      input.close()
}
```

java.lang.ArrayIndexOutOfBoundsException: 0
        at org.roaringbitmap.art.Node48.replaceChildren(Node48.java:279)
        at org.roaringbitmap.art.Art.deserialize(Art.java:359)
        at org.roaringbitmap.art.Art.deserialize(Art.java:356)
        at org.roaringbitmap.art.Art.deserializeArt(Art.java:286)
        at org.roaringbitmap.longlong.HighLowContainer.deserialize(HighLowContainer.java:193)
        at org.roaringbitmap.longlong.Roaring64Bitmap.deserialize(Roaring64Bitmap.java:598)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.liftedTree1$1(<pastie>:66)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:65)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:80)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:82)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:84)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:86)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:88)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:90)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:92)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:94)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:96)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:98)
        at $line34.$read$$iw$$iw$$iw$$iw$$iw.<init>(<pastie>:100)
        at $line34.$read$$iw$$iw$$iw$$iw.<init>(<pastie>:102)
        at $line34.$read$$iw$$iw$$iw.<init>(<pastie>:104)
        at $line34.$read$$iw$$iw.<init>(<pastie>:106)
        at $line34.$read$$iw.<init>(<pastie>:108)
        at $line34.$read.<init>(<pastie>:110)
        at $line34.$read$.<init>(<pastie>:114)
        at $line34.$read$.<clinit>(<pastie>)
        at $line34.$eval$.$print$lzycompute(<pastie>:7)
        at $line34.$eval$.$print(<pastie>:6)
        at $line34.$eval.$print(<pastie>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$20.apply(ILoop.scala:762)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$20.apply(ILoop.scala:762)
        at scala.tools.nsc.interpreter.IMain.withLabel(IMain.scala:116)
        at scala.tools.nsc.interpreter.ILoop.interpretCode$1(ILoop.scala:762)
        at scala.tools.nsc.interpreter.ILoop.pasteCommand(ILoop.scala:776)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$standardCommands$9.apply(ILoop.scala:217)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$standardCommands$9.apply(ILoop.scala:217)
        at scala.tools.nsc.interpreter.LoopCommands$LineCmd.apply(LoopCommands.scala:62)
        at scala.tools.nsc.interpreter.ILoop.colonCommand(ILoop.scala:698)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:689)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:425)
        at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply$mcZ$sp(SparkILoop.scala:285)
        at org.apache.spark.repl.SparkILoop.runClosure(SparkILoop.scala:159)
        at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:182)
        at org.apache.spark.repl.Main$.doMain(Main.scala:78)
        at org.apache.spark.repl.Main$.main(Main.scala:58)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by lemire** [comment]
@nbatra Please specify the version you are using.

**Comment by nbatra** [comment]
0.9.15

**Comment by weijietong** [comment]
@nbatra please try the latest version 0.9.16 to re-generate ,serialize, deserialize.

**Comment by weijietong** [comment]
Could you share a small data size to reproduce this bug ?

**Comment by richardstartin** [comment]
As an aside, it doesn’t sound like Roaring64Bitmap is a good choice for your data - storing 50M 64 bit values without compression would require 0.37GB and you say the bitmap file is larger than 1.5GB. It’s possible this is due to deficiencies in Roaring64Bitmap, but it’s likely your data is highly random and not amenable to prefix compression.

**Comment by richardstartin** [comment]
I think issues like this (which are frequently reported) indicate that Roaring64Bitmap needs randomised testing.

**Comment by weijietong** [comment]
We do have some randomised testing in `TestRoaring64Bitmap`(e.g. `testAllKindOfNodeTypesSerDeser()`), but seems we can't always execute it .

**Comment by richardstartin** [comment]
That test is seeded, so will never discover new failures. There isn’t a test which actually verifies the value of MAX_DEPTH is 7: if you change it back to 6 (or to 5?) all existing tests will pass. I suggest extending the fuzz-tests module to find failures and reduce them to minimal unit tests.

**Comment by weijietong** [comment]
Without seed, 100000 times `RepeatedTest` to run `testAllKindOfNodeTypesSerDeser`, still not reproduce this bug.

**Comment by richardstartin** [comment]
The test only puts 10000 elements into the bitmap and doesn't vary the distribution so I wouldn't expect much from it.

**Comment by lemire** [comment]
It is optimistic to rely solely on fuzz testing. In my view, fuzz testing is a way to find *new* bugs. It is not sufficient by itself.

**Comment by blacelle** [comment]
> I suggest extending the fuzz-tests module to find failures and reduce them to minimal unit tests.

It was @richardstartin point. @richardstartin do you a specific pointer in RoaringBitmap fuzz tests to help building satisfying fuzz tests for 64bits implementations?

**Comment by lemire** [comment]
Note that I am willing to volunteer a machine/server for running tests during days and weeks and months if someone builds the framework to run the tests in an extended manner.

**Comment by nbatra** [comment]
Thank you, everyone, for your help;  sincerely appreciate it.

We tried regenerating the Roaring64Bitmap with the 0.9.16 version, getting the following exception when deserializing.

@richardstartin You are correct; the dataset (long values) we are using to generate the Roaring64Bitmap is randomized. Do you recommend using any other API for the random long values?

@weijietong Pasting the same long values below for reference 

 
```
at org.roaringbitmap.art.Node256.replaceChildren(Node256.java:192)
	at org.roaringbitmap.art.Art.deserialize(Art.java:361)
	at org.roaringbitmap.art.Art.deserialize(Art.java:358)
	at org.roaringbitmap.art.Art.deserializeArt(Art.java:288)
	at org.roaringbitmap.longlong.HighLowContainer.deserialize(HighLowContainer.java:193)
	at org.roaringbitmap.longlong.Roaring64Bitmap.deserialize(Roaring64Bitmap.java:598)
	at jsm.nick.spark.aup.TestRoaringBitMap$.readRoaringBitMap(TestRoaringBitMap.scala:48)
	at jsm.nipun.spark.aup.TestRoaringBitMap$.delayedEndpoint$jsm$nick$spark$aup$TestRoaringBitMap$1(TestRoaringBitMap.scala:25)
	at jsm.nick.spark.aup.TestRoaringBitMap$delayedInit$body.apply(TestRoaringBitMap.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
```

```
2351366661281254203
3347833650324515202
2622018577097268341
3347833650324515202
8548819995241984624
3347833650324515202
8722462974327899589
3347833650324515202
8722462974327899589
3347833650324515202
4447021802872659705
8473455818089590301
4447021802872659705
3456378592715723645
8213581882446042785
3456378592715723645
8213581882446042785
3456378592715723645
8213581882446042785
3456378592715723645
7335300660388057310
3456378592715723645
7335300660388057310
3456378592715723645
7335300660388057310
3456378592715723645
7335300660388057310
3456378592715723645
3352760478264190180
3146392964891588747
3352760478264190180
4482910659919169160
9178053851694887725
4482910659919169160
9178053851694887725
4482910659919169160
3311480970200616182
4482910659919169160
3311480970200616182
4482910659919169160
3311480970200616182
2627563946890128767
8522492249295816203
2822952062611815514
2336227912836795131
2822952062611815514
2336227912836795131
2822952062611815514
9135891767469306255
4192145808247519474
8767581698184340700
4192145808247519474
8767581698184340700
4192145808247519474
8767581698184340700
8236272075658692073
8767581698184340700
8236272075658692073
8767581698184340700
8236272075658692073
8767581698184340700
8236272075658692073
8767581698184340700
8236272075658692073
8767581698184340700
8236272075658692073
8767581698184340700
2323904554171780770
8767581698184340700
2323904554171780770
8767581698184340700
2323904554171780770
8767581698184340700
2323904554171780770
8767581698184340700
2323904554171780770
8767581698184340700
2323904554171780770
8767581698184340700
2323904554171780770
8767581698184340700
2323904554171780770
8767581698184340700
7616407085438244831
8767581698184340700
7616407085438244831
8767581698184340700
7616407085438244831
8767581698184340700
2772651432579696927
8767581698184340700
2772651432579696927
8767581698184340700
4175419832642043602
8767581698184340700
4025662034158645714
8767581698184340700
4025662034158645714
8767581698184340700
7749192332270163546
8767581698184340700
7749192332270163546
8767581698184340700
2604036174381746721
8767581698184340700
2604036174381746721
8767581698184340700
3219936104138368522
8767581698184340700
2536134745877151734
8767581698184340700
2536134745877151734
8767581698184340700
3265411943207375309
8767581698184340700
6939310350090960479
8767581698184340700
7857035074994203397
8767581698184340700
3273395066482961175
3520868679567637773
3273395066482961175
3520868679567637773
3273395066482961175
7116647280826104776
3273395066482961175
7116647280826104776
7384930537499005349
7116647280826104776
7289058957308909553
3046775224192306560
8820335386768144754
3046775224192306560
4486023009370709294
3046775224192306560
4584173959049112749
3046775224192306560
8157738196719036695
3046775224192306560
8157738196719036695
3046775224192306560
7061377420732154674
3046775224192306560
2653935962758052092
3046775224192306560
2653935962758052092
3046775224192306560
2653935962758052092
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
4264456340579679772
3046775224192306560
2956868735646876284
3046775224192306560
7396623929707083831
3046775224192306560
7396623929707083831
3046775224192306560
7396623929707083831
3046775224192306560
3478363374105814920
3046775224192306560
3478363374105814920
3046775224192306560
3478363374105814920
3046775224192306560
3478363374105814920
3046775224192306560
3478363374105814920
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3046775224192306560
7320444253523084088
3193097377519195535
7320444253523084088
3193097377519195535
7320444253523084088
3193097377519195535
7320444253523084088
3193097377519195535
7320444253523084088
2392596897858290157
7320444253523084088
2392596897858290157
7320444253523084088
8072631148987945486
7320444253523084088
3833177139822889366
7320444253523084088
7385743003377315004
7320444253523084088
7385743003377315004
7320444253523084088
7385743003377315004
7320444253523084088
7385743003377315004
7320444253523084088
7385743003377315004
7320444253523084088
7385743003377315004
2310718140759970042
7385743003377315004
2310718140759970042
3659282179564804294
2310718140759970042
7200555484363442408
2767064928663441698
7200555484363442408
2767064928663441698
7200555484363442408
7626146837472420971
4226428831288938276
3383544298452034713
3847963704656701833
3383544298452034713
3847963704656701833
3383544298452034713
3847963704656701833
3383544298452034713
3847963704656701833
3313418977094209661
8903946139627052182
3115010745290495472
8903946139627052182
3115010745290495472
2566742302838874927
2319900993179976012
7088443800570977464
4006929799482189803
7339033617251934968
7762413140111713354
7339033617251934968
7762413140111713354
7339033617251934968
7762413140111713354
7339033617251934968
7762413140111713354
7339033617251934968
7762413140111713354
7339033617251934968
7762413140111713354
7339033617251934968
7762413140111713354
7339033617251934968
7762413140111713354
4574809117257160232
7762413140111713354
2426043396503393864
7762413140111713354
7938546006275072715
7762413140111713354
7938546006275072715
7762413140111713354
4513631027719435251
7762413140111713354
4513631027719435251
7762413140111713354
4513631027719435251
7762413140111713354
4513631027719435251
7762413140111713354
2388563786467926876
7762413140111713354
4521594795077099759
7762413140111713354
4521594795077099759
7762413140111713354
2838082265280105334
7762413140111713354
4499588819554635462
7762413140111713354
4499588819554635462
7762413140111713354
4499588819554635462
7762413140111713354
4499588819554635462
7762413140111713354
4499588819554635462
7762413140111713354
8680869698503658225
7762413140111713354
8680869698503658225
7762413140111713354
8680869698503658225
7762413140111713354
3761524019346694983
8677012169505018184
3761524019346694983
8677012169505018184
3761524019346694983
8612306537490966951
3761524019346694983
8612306537490966951
3761524019346694983
8612306537490966951
3761524019346694983
8612306537490966951
3761524019346694983
8612306537490966951
4567309530113889598
8612306537490966951
7738915037513480114
8612306537490966951
7738915037513480114
8612306537490966951
2963549505964561521
8612306537490966951
2963549505964561521
8612306537490966951
3575808687112398263
8263812039761947611
3575808687112398263
8263812039761947611
3372701056520090160
8263812039761947611
3372701056520090160
2512424464812064826
3372701056520090160
2744398752232597041
3372701056520090160
2744398752232597041
2412853487183370250
3672525730613094726
2412853487183370250
3672525730613094726
3409953566998544218
3672525730613094726
3409953566998544218
4523099219573339858
3409953566998544218
4523099219573339858
8227017574516971593
4523099219573339858
8227017574516971593
4523099219573339858
8227017574516971593
4523099219573339858
8227017574516971593
4523099219573339858
8564993182018657939
4523099219573339858
8564993182018657939
4523099219573339858
8564993182018657939
4523099219573339858
2794222733758960341
4523099219573339858
2794222733758960341
4523099219573339858
2485949770257923462
4523099219573339858
3017068948759721484
4523099219573339858
3328766423071551487
4523099219573339858
3328766423071551487
4523099219573339858
3328766423071551487
4523099219573339858
8344446547011377697
4523099219573339858
2908746420643045951
4523099219573339858
2908746420643045951
4523099219573339858
2908746420643045951
4523099219573339858
2908746420643045951
4523099219573339858
7234571261485787876
4523099219573339858
7234571261485787876
4523099219573339858
7234571261485787876
4523099219573339858
2968412913981003884
4523099219573339858
2968412913981003884
4523099219573339858
2968412913981003884
4523099219573339858
8922570164491162225
4523099219573339858
8922570164491162225
4523099219573339858
8922570164491162225
4523099219573339858
8801125576886851376
4523099219573339858
8401222080673619423
4523099219573339858
8401222080673619423
4523099219573339858
7131466821702654073
4523099219573339858
7131466821702654073
4523099219573339858
4526863920719332575
4523099219573339858
3153531430697485545
4523099219573339858
4156618281340992619
4523099219573339858
4156618281340992619
4523099219573339858
4156618281340992619
4523099219573339858
4156618281340992619
4523099219573339858
8615287574359524993
4523099219573339858
3839453212970657264
4523099219573339858
3839453212970657264
4523099219573339858
2606040252411981579
4523099219573339858
2606040252411981579
4523099219573339858
3738249562633584677
4523099219573339858
3738249562633584677
4523099219573339858
3738249562633584677
4523099219573339858
3733227137000836898
4523099219573339858
2355735646106753716
4523099219573339858
2355735646106753716
4523099219573339858
2355735646106753716
4523099219573339858
2355735646106753716
4523099219573339858
2355735646106753716
4523099219573339858
2355735646106753716
4523099219573339858
2355735646106753716
4523099219573339858
2355735646106753716
4523099219573339858
2795944566036858091
4523099219573339858
2795944566036858091
4523099219573339858
2795944566036858091
4523099219573339858
2795944566036858091
4523099219573339858
2795944566036858091
4523099219573339858
2795944566036858091
4523099219573339858
2795944566036858091
4523099219573339858
2795944566036858091
4523099219573339858
2795944566036858091
4523099219573339858
2795944566036858091
4523099219573339858
7913772012981717148
4523099219573339858
7913772012981717148
4523099219573339858
7913772012981717148
4523099219573339858
7647778722840820496
4523099219573339858
7647778722840820496
4523099219573339858
7647778722840820496
4523099219573339858
4079413841510870531
4523099219573339858
3492982323343611571
4523099219573339858
3492982323343611571
4523099219573339858
7859490936416192434
4523099219573339858
9141269486113850471
4523099219573339858
9141269486113850471
4523099219573339858
9141269486113850471
4523099219573339858
7980271243446300247
4523099219573339858
3454499680261572547
4523099219573339858
3454499680261572547
4523099219573339858
3454499680261572547
4523099219573339858
3454499680261572547
4523099219573339858
3454499680261572547
4523099219573339858
2310975498824828130
4523099219573339858
2697714615650444541
4523099219573339858
3812254185640133297
4523099219573339858
3812254185640133297
4523099219573339858
4047664750751274785
4523099219573339858
4047664750751274785
4523099219573339858
4047664750751274785
4523099219573339858
4047664750751274785
4523099219573339858
4047664750751274785
4523099219573339858
2323401723087123707
4523099219573339858
2323401723087123707
4523099219573339858
8338051558719920091
4523099219573339858
3388640361474293231
3239868038255191515
3388640361474293231
3239868038255191515
3388640361474293231
4065815423675672140
3388640361474293231
4065815423675672140
3388640361474293231
4065815423675672140
8997841665279285823
3508422609168347361
2502980414592121025
3508422609168347361
2438683565120321208
3209510342136357212
4588161731628406804
4349933283309605297
4588161731628406804
2801974945613973526
4588161731628406804
2801974945613973526
3998579724795284102
2801974945613973526
3998579724795284102
7205436482321897623
3998579724795284102
7205436482321897623
2997887017891594102
2732403266459061290
2730791364103662889
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
2732403266459061290
3091607002425380837
3757307373397099672
3091607002425380837
7172060756039738887
3091607002425380837
7172060756039738887
3091607002425380837
7172060756039738887
3091607002425380837
7172060756039738887
3091607002425380837
7172060756039738887
3091607002425380837
7172060756039738887
3091607002425380837
8975578285866325481
3929557041345829219
8975578285866325481
9134196539264580793
8975578285866325481
9134196539264580793
8975578285866325481
9134196539264580793
8975578285866325481
9134196539264580793
8975578285866325481
9134196539264580793
8975578285866325481
9134196539264580793
7068726940865314738
9134196539264580793
7068726940865314738
9134196539264580793
7068726940865314738
9134196539264580793
7068726940865314738
7277458034054616061
7068726940865314738
7277458034054616061
7068726940865314738
7277458034054616061
7068726940865314738
4351910813217384050
7068726940865314738
4351910813217384050
7068726940865314738
4351910813217384050
7068726940865314738
9203820201394761902
7068726940865314738
3734765113842626512
2755975155779738628
3287495360691278097
2755975155779738628
3287495360691278097
2755975155779738628
4075896095334737388
2755975155779738628
4075896095334737388
2755975155779738628
2449389489404279020
2755975155779738628
2449389489404279020
2755975155779738628
2449389489404279020
2755975155779738628
7397912392392391691
2755975155779738628
3461331627899097156
4604360460148081008
3461331627899097156
4604360460148081008
3598772485068343989
4604360460148081008
7419629073759555289
4604360460148081008
7419629073759555289
4604360460148081008
7419629073759555289
4604360460148081008
7419629073759555289
4604360460148081008
4537998817447038665
4604360460148081008
7462600960963377703
4604360460148081008
3902710114837139750
4604360460148081008
3902710114837139750
3007161919609822426
3902710114837139750
3007161919609822426
4545793534754190594
3007161919609822426
4545793534754190594
2998652640581215769
4545793534754190594
7576393045586854757
4545793534754190594
8919855364365079692
4545793534754190594
8919855364365079692
4545793534754190594
8919855364365079692
2835476481854750012
2716473165814686406
2835476481854750012
2716473165814686406
7053389084367431541
2519681705701340205
8716073691451778903
2914334903792600046
3870499020567819390
2914334903792600046
3870499020567819390
8540589100396807394
3870499020567819390
4115031630114827897
3384247333850564231
4240725418956143268
7591691074707789613
3356006706022057963
7591691074707789613
4414737825488286749
4019938764722426925
6920602119735974368
2839207382381498398
8673527927440847200
7770741149207855795
3615220770516354947
2831212759017686053
7041065122735956363
8330230789547624519
7041065122735956363
8330230789547624519
7041065122735956363
8330230789547624519
7041065122735956363
8330230789547624519
7041065122735956363
8330230789547624519
7041065122735956363
8330230789547624519
7041065122735956363
8330230789547624519
2704066103998084747
8330230789547624519
2704066103998084747
8330230789547624519
2704066103998084747
7155465984666246346
4099339109270737031
7518685302254244001
4099339109270737031
3824895707277541341
4099339109270737031
3824895707277541341
4099339109270737031
7296237876976683184
2877765039338781004
7296237876976683184
2877765039338781004
3839637027140133178
2877765039338781004
3839637027140133178
2877765039338781004
3839637027140133178
2877765039338781004
3839637027140133178
2877765039338781004
3424688356869614049
2677482314084118447
3424688356869614049
2677482314084118447
3424688356869614049
2677482314084118447
3804517267070760946
2677482314084118447
3804517267070760946
2677482314084118447
3342149489450035267
3531950768573766074
3712390272291675788
3531950768573766074
3712390272291675788
3531950768573766074
3712390272291675788
3597878979387797337
3712390272291675788
3802295313082117518
3712390272291675788
3802295313082117518
3712390272291675788
2499737315223420410
3712390272291675788
3923815854396880509
3712390272291675788
3744080136363249542
3712390272291675788
9061773291311561640
3712390272291675788
8642621519148426257
3712390272291675788
7791165461594958028
3712390272291675788
7791165461594958028
3712390272291675788
7791165461594958028
3712390272291675788
7791165461594958028
3712390272291675788
3144499765460072464
3712390272291675788
3144499765460072464
3712390272291675788
3190809545326004749
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3733159432804183975
3712390272291675788
3330476159642147653
3712390272291675788
3330476159642147653
3712390272291675788
3330476159642147653
3712390272291675788
3330476159642147653
3712390272291675788
7236200346100449559
3712390272291675788
7236200346100449559
3712390272291675788
7236200346100449559
3712390272291675788
7236200346100449559
3712390272291675788
8687917987512643521
3712390272291675788
8687917987512643521
3712390272291675788
3015732143686559573
3712390272291675788
3015732143686559573
3712390272291675788
4016311586135873654
3712390272291675788
4016311586135873654
3712390272291675788
3583993184072913316
3712390272291675788
2677178388528186031
3712390272291675788
7159427289075341483
3712390272291675788
7159427289075341483
3712390272291675788
7159427289075341483
7418198795886860913
7159427289075341483
7418198795886860913
7159427289075341483
7810096432760014583
7159427289075341483
3121487527753958666
7159427289075341483
3062835425538392623
7159427289075341483
7026004824274760328
7040811293075035169
7026004824274760328
8414597652816776373
2349442499360768719
3358517433230821217
2349442499360768719
2324511711890996656
2349442499360768719
2324511711890996656
2349442499360768719
3162681671122504309
2349442499360768719
7891751678230561005
2349442499360768719
7891751678230561005
2349442499360768719
2698098739033681461
2349442499360768719
2907695704736718418
2349442499360768719
2907695704736718418
2349442499360768719
2907695704736718418
2349442499360768719
2907695704736718418
7236326885761788820
2907695704736718418
7236326885761788820
2907695704736718418
3909259003947466755
2907695704736718418
3909259003947466755
2907695704736718418
3909259003947466755
2907695704736718418
```

**Comment by weijietong** [comment]
@nbatra I can't reproduce the issue using your supplied data. I also change `testAllKindOfNodeTypesSerDeser`'s number size from `10000` to `500000` to run random tests , still not found this case.

**Comment by weijietong** [comment]
@nbatra try to change the HDFS file system to local file system to see what will happen.

**Comment by richardstartin** [comment]
@nbatra this library prefix-compresses sets of integers, it makes a bet that the higher order bits are mostly repeated within the set, so can be stripped off the raw values and deduplicated. If you have random data that isn’t true, and the bitmaps will typically be larger than the data. 

I would recommend simply not to use the library for purely random data. Depending on density, you might be better off with an array or an uncompressed bitset.

**Comment by lemire** [comment]
@nbatra Note that random 64-bit integers cannot be compressed. That's a general principle. If they could be compressed, then they would not be compressible. I believe that this is explained in our README file but it is just generally true.

**Comment by nbatra** [comment]
Thank you, @richardstartin @lemire 

@weijietong, I think I know the issue; as you suggested, I tried creating a Roaring64BitMap locally. The serialization process took a long time to complete; (for me, it took forever), and I ended up exiting the process in the middle. After shutting down, I noticed a partial Roaring64BitMap file was present in the folder. 

I think the same is happening with our spark job; we (spark tasks) are creating 1000s of Roaring64BitMap files. Because the serialization process is long, spark-tasks are timing out, leaving the partially generated files on the hdfs directory. 

I probably should have done this test first before reaching out. Apologies for the confusion and appreciate everyones help here.

**Comment by weijietong** [comment]
Ok,we can close this issue now.By the way,the serialization should not take so many times.From the codes you showed ,the output or input stream should be buffered.

**Comment by blacelle** [comment]
Shouldn't have the deserialization process failed in case of an incomplete input?

**Comment by weijietong** [comment]
To fail,we need to know the input file is crushed first. Then we maybe need some techs like checksum. That would be heavy to the ser/deser. Also maybe we need to support the random seek stream inteface.

**Comment by blacelle** [comment]
>  That would be heavy to the ser/deser. 

We may simply indicates the number of output bytes (quite poor, but very light and catch most form of interruption (but not corruption)). I never went through RoaringBitmap ser-deser protocol: does it have any form of checksum @lemire ?

**Comment by richardstartin** [comment]
Checksumming is something the user can do themselves if they want to, and they can even choose the algorithm that way. I would prefer to keep the protocol stream oriented so sub linear memory can be used if desired.

**Comment by larsk-db** [comment]
> Checksumming is something the user can do themselves if they want to, and they can even choose the algorithm that way. I would prefer to keep the protocol stream oriented so sub linear memory can be used if desired.

I agree with this. 

We already do that in our code also including some other fields we are writing and it'd probably slow it down significantly to have the checksum calculation duplicated.
